#!/usr/bin/env python3

from os import chmod, environ, getcwd, makedirs, unlink
from os.path import basename, dirname, join, relpath
from shutil import which
from socket import AF_UNIX, SOCK_STREAM, socket
from socketserver import BaseRequestHandler, UnixStreamServer
from subprocess import PIPE, Popen, run
from sys import argv, stderr, stdin, stdout
from time import sleep
from typing import List


#################### ########### ####################
#################### INIT Region ####################
#################### ########### ####################


__dir__ = dirname(__file__)
__bin__ = join(dirname(__file__), "bin")
__name__ = basename(argv[1])
__args__ = argv[2:]
__socket_path__ = join(__dir__, "socket", "cp.socket")


def path_mask() -> None:
  paths = (path
           for path in environ["PATH"].split(":")
           if path != __bin__)
  environ["PATH"] = ":".join(paths)


#################### ########### ####################
#################### Copy Region ####################
#################### ########### ####################


def cp(data: bytes) -> None:
  if environ.get("TMUX"):
    run(["tmux", "load-buffer", "-"], input=data)

  if which("pbcopy"):
    run(["pbcopy"], input=data)

  elif environ.get("WAYLAND_DISPLAY") and which("wl-copy"):
    run(["wl-copy"], input=data)

  elif environ.get("DISPLAY") and which("xclip"):
    run(["xclip"], input=data)


def rcp(data: bytes) -> None:
  with socket(AF_UNIX, SOCK_STREAM) as sock:
    sock.connect(__socket_path__)
    sock.sendall(data)
    sock.sendall(b'\0\n')


def cp_data(data: bytes) -> None:
  cp(data)
  if environ.get("SSH_TTY"):
    rcp(data)


def copy() -> None:
  data: bytes = stdin.read().strip("\n").encode()
  cp_data(data)


#################### ############ ####################
#################### Paste Region ####################
#################### ############ ####################


def paste() -> None:
  if which("pbpaste"):
    run(["pbpaste"])

  elif environ.get("WAYLAND_DISPLAY") and which("wl-paste"):
    run(["wl-paste"])

  elif environ.get("DISPLAY") and which("xclip"):
    run(["xclip", "-out"])

  elif environ.get("TMUX"):
    run(["xclip", "-out"])
    run(["tmux", "save-buffer", "-"])

  else:
    print("⚠️ No clipboard integration ⚠️", file=stderr)
    exit(1)


#################### ########### ####################
#################### CSSH Region ####################
#################### ########### ####################


def cssh_cmd() -> List[str]:
  lookup = {"cssh": ["ssh"],
            "cdocker": ["docker", "exec"]}
  return lookup[__name__]


def cssh_prog() -> str:
  home = environ["HOME"]
  canonical = join(__bin__, "csshd")

  if canonical.startswith(home):
    prog = relpath(canonical, home)
    return f"$HOME/{prog}"
  else:
    return canonical


def cssh_run(args: List[str]) -> None:
  cmd = cssh_cmd()
  prog = cssh_prog()
  exe = [*cmd, *args, "sh", "-c", f'"{prog}"']
  process: Popen = Popen(exe,
                         stdout=PIPE,
                         stderr=PIPE)
  buf = bytearray()

  while True:
    code = process.poll()
    if code:
      print(f"{' '.join(exe)}\ndaemon exited - {code}", file=stderr)
      print(process.stderr.read().decode(), file=stderr)
      return

    line: bytes = process.stdout.readline()
    for b in line:
      if b == 0:
        cp_data(buf)
        buf.clear()
        break
      else:
        buf.append(b)


def cssh() -> None:
  while True:
    cssh_run(__args__)
    sleep(1)
    print("\a")


#################### ############ ####################
#################### CSSHD Region ####################
#################### ############ ####################


def ready_socket(path: str) -> None:
  try:
    unlink(path)
  except IOError:
    pass


def csshd() -> None:
  class Handler(BaseRequestHandler):
    def handle(self) -> None:
      with self.request.makefile() as fd:
        data: str = fd.read()
        stdout.write(data)
        stdout.flush()

  ready_socket(__socket_path__)
  with UnixStreamServer(__socket_path__, Handler) as srv:
    srv.serve_forever()


#################### ########### ####################
#################### Main Region ####################
#################### ########### ####################


def is_copy() -> bool:
  if __name__ in {"c", "pbcopy", "wl-copy"}:
    return True
  elif __name__ == "xclip" and set(__args__).isdisjoint({"-o", "-out"}):
    return True
  else:
    return False


def is_paste() -> bool:
  if __name__ in {"p", "pbpaste", "wl-paste"}:
    return True
  elif __name__ == "xclip" and not set(__args__).isdisjoint({"-o", "-out"}):
    return True
  else:
    return False


def main() -> None:
  path_mask()

  if __name__ in {"cssh", "cdocker"}:
    cssh()
  elif __name__ == "csshd":
    csshd()
  elif is_paste():
    paste()
  elif is_copy():
    copy()
  else:
    print(f"Unknown -- {__name__} {' '.join(__args__)}", file=stderr)
    exit(1)


try:
  main()
except KeyboardInterrupt:
  pass

